### ISSUE TITLE
[SUGGESTION] Restrict flag

### ISSUE THREAD

**Issue by langw0ww** [pandathebeasty/cs2_goldmember#1]
I suggest to add a restriction for special flag like ``@vip``

Also, in chat shows "your benefits: weapon_smoke, weapon_flash" instead of "your benefits: smoke, flash"

**Comment by pandathebeasty** [comment]
Give more details related to flags!
Related to other remark, the plugin will take the items name from the list and that is the reason is showing weapon_name instead of name :)

**Comment by pandathebeasty** [comment]
Added here [RELEASE 0.06](https://github.com/pandathebeasty/cs2_goldmember/releases/tag/0.0.6)
